### PR TITLE
Implement special mode (tested with ATXM20M2V1B/BRP069A42)

### PR DESCRIPTION
**Pull request by b-straub**
Implement the special modes CLEAN, POWERFUL and ECONOMY.

### CODE REVIEW

**Comment by Apollon77** [comment]
Hey, cool, I never understood how they tick (and don't had the time to figure it out till now) :-)

Would you be so kind to also add documentation for the new method (and especially the "values" object and the possible values in there to the README?!

**Comment by b-straub** [comment]
Updated the request and added changes to README.

**Comment by b-straub** [comment]
Please revise the code, I made an one week self educating JS/TS crash curse in order to implement a better Daikin Homebridge-Plugin (in progress). Coming from C++/C#/Swift I might not understand all concepts well enough yet.

**Comment by Apollon77** [comment]
I will check this afternoon, but first look was good :-)
Thank you for your participation

**Comment by Apollon77** [comment]
released as 1.1.0 on npm

**Pull request merged**
